name: Build secilc for Android

on:
  push:
    tags: ['v*']
  workflow_dispatch:

jobs:
  build-android:
    name: Build secilc for Android
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        target: [arm64-v8a, armeabi-v7a, x86, x86_64]
    
    steps:
    - name: Checkout workflow (not needed for source)
      uses: actions/checkout@v4
    
    - name: Set up Android NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r28c
        
    - name: Set up build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential automake autoconf libtool pkg-config
        # 安装 xmlto 和相关文档生成工具
        sudo apt-get install -y xmlto docbook-utils docbook-xsl xsltproc
        
    - name: Build for ${{ matrix.target }}
      run: |
        # 设置 Android 工具链
        export ANDROID_NDK_HOME=$ANDROID_NDK_ROOT
        export TOOLCHAIN=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64
        
        # 根据目标架构设置环境变量
        case "${{ matrix.target }}" in
          arm64-v8a)
            export TARGET=aarch64-linux-android
            export API=21
            ;;
          armeabi-v7a)
            export TARGET=armv7a-linux-androideabi
            export API=21
            ;;
          x86)
            export TARGET=i686-linux-android
            export API=21
            ;;
          x86_64)
            export TARGET=x86_64-linux-android
            export API=21
            ;;
        esac
        
        export AR=$TOOLCHAIN/bin/llvm-ar
        export CC=$TOOLCHAIN/bin/${TARGET}${API}-clang
        export CXX=$TOOLCHAIN/bin/${TARGET}${API}-clang++
        export LD=$TOOLCHAIN/bin/ld
        export RANLIB=$TOOLCHAIN/bin/llvm-ranlib
        export STRIP=$TOOLCHAIN/bin/llvm-strip
        
        # 克隆 SELinux 项目（包含 secilc 和 libsepol）
        git clone https://github.com/SELinuxProject/selinux.git
        cd selinux
        
        # 切换到稳定版本（根据需要调整）
        git checkout main
        
        # 首先编译 libsepol（secilc 的依赖）
        echo "Building libsepol..."
        cd libsepol
        make CC="$CC" AR="$AR" RANLIB="$RANLIB" STRIP="$STRIP" \
             CFLAGS="-D_GNU_SOURCE -O2 -fPIC"

        # 创建符号链接解决头文件路径问题
        echo "Creating symlink for header files..."
        mkdir -p include/sepol
        ln -s $(pwd)/cil/include/cil include/sepol/cil
        
        # 编译 secilc
        echo "Building secilc..."
        cd ../secilc
        
        make CC="$CC" AR="$AR" RANLIB="$RANLIB" STRIP="$STRIP" \
             CFLAGS="-D_GNU_SOURCE -O2 -fPIC -I../libsepol/include -I../libsepol/cil/include" \
             LDFLAGS="-L../libsepol/src" \
             LIBS="-lsepol"
        
        # 检查编译是否成功
        if [ ! -f "secilc" ]; then
          echo "secilc binary not found after compilation!"
          exit 1
        fi
        
        # 准备输出目录
        mkdir -p ../android-build/${{ matrix.target }}
        cp secilc secil2conf secil2tree ../android-build/${{ matrix.target }}/
        $STRIP ../android-build/${{ matrix.target }}/secilc
        $STRIP ../android-build/${{ matrix.target }}/secil2conf
        $STRIP ../android-build/${{ matrix.target }}/secil2tree
        
        echo "Build completed successfully for ${{ matrix.target }}"
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: secilc-android-${{ matrix.target }}
        path: selinux/android-build/${{ matrix.target }}/
        retention-days: 7

  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build-android
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
    
    - name: Create release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        files: |
          artifacts/secilc-android-arm64-v8a/secilc
          artifacts/secilc-android-arm64-v8a/secil2conf
          artifacts/secilc-android-arm64-v8a/secil2tree
          artifacts/secilc-android-armeabi-v7a/secilc
          artifacts/secilc-android-armeabi-v7a/secil2conf
          artifacts/secilc-android-armeabi-v7a/secil2tree
          artifacts/secilc-android-x86/secilc
          artifacts/secilc-android-x86/secil2conf
          artifacts/secilc-android-x86/secil2tree
          artifacts/secilc-android-x86_64/secilc
          artifacts/secilc-android-x86_64/secil2conf
          artifacts/secilc-android-x86_64/secil2tree
