name: Build secilc for Android

on:
  push:
    tags: ['v*']
  workflow_dispatch:

jobs:
  build-android:
    name: Build secilc for Android
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        target: [arm64-v8a, armeabi-v7a, x86, x86_64]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Android NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: '25.2.9519653'
    
    - name: Set up build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential automake autoconf libtool pkg-config
    
    - name: Build for ${{ matrix.target }}
      run: |
        # 设置 Android 工具链
        export ANDROID_NDK_HOME=$ANDROID_HOME/ndk/25.2.9519653
        export TOOLCHAIN=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64
        
        # 根据目标架构设置环境变量
        case "${{ matrix.target }}" in
          arm64-v8a)
            export TARGET=aarch64-linux-android
            export API=21
            ;;
          armeabi-v7a)
            export TARGET=armv7a-linux-androideabi
            export API=21
            ;;
          x86)
            export TARGET=i686-linux-android
            export API=21
            ;;
          x86_64)
            export TARGET=x86_64-linux-android
            export API=21
            ;;
        esac
        
        export AR=$TOOLCHAIN/bin/llvm-ar
        export CC=$TOOLCHAIN/bin/${TARGET}${API}-clang
        export CXX=$TOOLCHAIN/bin/${TARGET}${API}-clang++
        export LD=$TOOLCHAIN/bin/ld
        export RANLIB=$TOOLCHAIN/bin/llvm-ranlib
        export STRIP=$TOOLCHAIN/bin/llvm-strip
        
        # 编译 libsepol（secilc 的依赖）
        git clone https://github.com/SELinuxProject/selinux.git
        cd selinux
        git checkout libsepol-3.5
        cd libsepol
        make CC="$CC" AR="$AR" RANLIB="$RANLIB" STRIP="$STRIP" \
             CFLAGS="-D_GNU_SOURCE -O2 -fPIC"
        
        # 编译 secilc
        cd ../..
        make CC="$CC" AR="$AR" RANLIB="$RANLIB" STRIP="$STRIP" \
             CFLAGS="-D_GNU_SOURCE -O2 -fPIC -I$(pwd)/selinux/libsepol/include" \
             LDFLAGS="-L$(pwd)/selinux/libsepol/src" \
             LIBS="-lsepol"
        
        # 重命名并复制二进制文件
        mkdir -p android-build/${{ matrix.target }}
        cp secilc android-build/${{ matrix.target }}/secilc
        $STRIP android-build/${{ matrix.target }}/secilc
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: secilc-android-${{ matrix.target }}
        path: android-build/${{ matrix.target }}/
        retention-days: 7

  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build-android
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
    
    - name: Create release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        files: |
          artifacts/secilc-android-arm64-v8a/secilc
          artifacts/secilc-android-armeabi-v7a/secilc
          artifacts/secilc-android-x86/secilc
          artifacts/secilc-android-x86_64/secilc
          
